### ISSUE TITLE
Is there a way to use this model for inference on tracks that are less than 5 seconds?

### ISSUE THREAD

**Issue by subhanjansaha** [faroit/CountNet#8]
Actually I am trying to prepare a real-time or near real-time system, which would select out a primary speaker from a track containing concurrent overlapping speakers, and this would further be the input to an ASR model. However, this particular pretrained model seems to only work for tracks that are 5 seconds or more in duration. Is there a way to overcome this? 
Would I have to train this model again? Will it hurt the MAE scores?

**Comment by faroit** [comment]
> However, this particular pretrained model seems to only work for tracks that are 5 seconds or more in duration.  Is there a way to overcome this?

yes, the CRNN model was trained on fixed 5 second inputs, the LSTM would work with less on inference.

>  Would I have to train this model again? Will it hurt the MAE scores?

yes, but it gets more difficult. See the plot from our paper here:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/72940/88778968-7ad92f80-d189-11ea-8780-78688d633ada.png">

less than 1 second will be hard - also because evaluation is hardly possible since there are not enough speech datasets with precise syllable-level annotations.

**Comment by faroit** [comment]
@subhanjansaha can this be closed?
